"""Argilla v2 settings for the Task 1 pilot: 10-item realism judgment.

Pattern 4 (binary judgment + confidence + optional notes), single labeler
(MIN_SUBMITTED = 1).

The labeler will see one review at a time and decide whether it is real or
synthetic, plus a 1-5 confidence rating. Hidden ground truth in
tasks/task_1_pilot/_truth.json is used by the coordinator for scoring,
never shown to the labeler.
"""
import argilla as rg


JUDGMENT_LABELS = ["real", "synthetic"]
MIN_SUBMITTED = 1

GUIDELINES = (
    "Read each review and decide whether you think it was written by a real "
    "student or generated by an AI. Then rate your confidence (1 = guessing, "
    "5 = certain). One-line cues in the notes field are welcome but optional. "
    "Length alone is not a reliable cue; focus on vocabulary, specificity, "
    "and whether the writer's flow feels uneven or polished."
)


def make_settings() -> "rg.Settings":
    return rg.Settings(
        guidelines=GUIDELINES,
        fields=[rg.TextField(name="text", title="Review", use_markdown=False)],
        questions=[
            rg.LabelQuestion(
                name="judgment",
                labels=JUDGMENT_LABELS,
                title="Your judgment",
                required=True,
            ),
            rg.RatingQuestion(
                name="confidence",
                values=[1, 2, 3, 4, 5],
                title="Confidence (1 = guessing, 5 = certain)",
                required=True,
            ),
            rg.TextQuestion(
                name="notes",
                title="One-line cue (optional)",
                required=False,
                use_markdown=False,
            ),
        ],
        distribution=rg.TaskDistribution(min_submitted=MIN_SUBMITTED),
    )
